# Generated by Django 4.0.6 on 2022-08-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('imgurl', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('storename', models.CharField(max_length=255)),
                ('storeurl', models.CharField(max_length=255)),
                ('storeid', models.CharField(max_length=255)),
            ],
        ),
    ]
