# Generated by Django 4.0.6 on 2022-08-03 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='imgurl',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='storeid',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='storename',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='storeurl',
            new_name='store_url',
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
